FIELD_MAPPING = {
    "ticket_type": "keyword",
    "number": "keyword",
    "state": "keyword",
    "created_date": "date",
    "last_updated_date": "date",
    "short_description": "text",
    "description": "text",
    "application": "keyword",
    "assignment_group": "keyword",
    "assigned_to": "keyword",
    "impact": "keyword",
    "priority": "keyword",
    "urgency": "keyword",
    "severity": "keyword",
    "resolved_by": "keyword",
    "updated_by": "keyword",
    "created_by": "keyword",
    "closed_at": "date",
    "resolved_at": "date",
    "work_notes": "text",
    "close_code": "keyword",
    "close_notes": "text",
    "closed_by": "keyword",
    "sys_id": "keyword",
    "reopened_by": "keyword",
    "comments_and_work_notes": "text"
}