mapping={
    "ticket_type": "sys_class_name",
    "number": "number",
    "state": "state",
    "created_date": "opened_at",
    "last_updated_date": "sys_updated_on",
    "short_description": "short_description",
    "description": "description",
    "application": "category",
    "assignment_group": "assignment_group",
    "assigned_to": "assigned_to",
    "impact": "impact",
    "priority": "priority",
    "urgency": "urgency",
    "severity": "severity",
    "resolved_by": "resolved_by",
    "updated_by": "sys_updated_by",
    "created_by": "sys_created_by",
    "closed_at": "closed_at",
    "resolved_at": "resolved_at",
    "work_notes": "work_notes",
    "close_code": "close_code",
    "close_notes": "close_notes",
    "closed_by": "closed_by",
    "sys_id": "sys_id",
    "reopened_by": "reopened_by",
    "comments_and_work_notes": "comments_and_work_notes"
}
